import Head from 'next/head'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>

      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keyword" content="nextjs, huntingcoder blog, hunting coder" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src='/sc.js' strategy='lazyOnload'></Script> */}


      <main className={styles.main}>
        <div className={styles.imagewrap}>
          {/* <Image className={styles.myImg} src="/homeimg.jfif" width={237} height={158} alt='' /> */}
          <img className={styles.myImg} src="/homeimg.jfif" width={237} height={158} alt="hunting coder" />
        </div>
        <h1 className={styles.title}>
          <span className='dummy'>&lt;HuntingCoder /&gt;</span>
        </h1>



        {/* <div className={`${styles1.con}${styles2.con}`}> */}
        <div>
          <h2 className={styles.h2}>Latest Blogs</h2>
          <div className="blogItem">
            <h3 className={styles.h3}>How to learn JavaScript in 2023?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h3 className={styles.h3}>How to learn JavaScript in 2023?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
            <button className={styles.btn}>Read more</button>
          </div>
          <div className="blogItem">
            <h3 className={styles.h3}>How to learn JavaScript in 2023?</h3>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>

        </div>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}